# Default values for oracle-standalone.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

image:
  repository: container-registry.oracle.com/database/enterprise
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "12.2.0.1-slim"
  
hostname: oracle-standalone
oracle_password: "Toughpass1!"

podSecurityContext:
  fsGroup: 54322

service:
  type: ClusterIP
  portListener: 1521
  portExpress: 5500

pvc:
  StorageClass: "csi-vmware"
  oradataaccessMode: ReadWriteOnce
  oradatasize: 50Gi
  oradatavolumeMode: Filesystem
