apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongodb-standalone.fullname" . }}
  labels:
    {{- include "mongodb-standalone.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      {{- include "mongodb-standalone.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mongodb-standalone.selectorLabels" . | nindent 8 }}
    spec:
      hostname: {{ .Values.hostname}}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccount: {{ include "mongodb-standalone.fullname" . }}
      serviceAccountName: {{ include "mongodb-standalone.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containers.ports.containerPort}}
          env:
            - name: MONGODB_INITDB_ROOT_USERNAME
              valueFrom:
               secretKeyRef:
                name: {{ include "mongodb-standalone.fullname" . }}-secret
                key: {{  template "mongodb.rootusername" . }}
            - name: MONGODB_INITDB_ROOT_PASSWORD
              valueFrom:
               secretKeyRef:
                name: {{ include "mongodb-standalone.fullname" . }}-secret
                key: {{  template "mongodb.rootpassword" . }}
          volumeMounts:
            - mountPath: /data/configdb
              name: configdb
            - mountPath: /data/db
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
           claimName: {{ include "mongodb-standalone.fullname" . }}-data
        - name: configdb
          persistentVolumeClaim:
           claimName: {{ include "mongodb-standalone.fullname" . }}-configdb
