apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.hostname }}-secret
  labels:
    {{- include "mongodb-standalone.labels" . | nindent 4 }}
type: Opaque
data:
  mongo_initdb_root_username : {{ .Values.mongo_initdb_root_username | b64enc | quote}}
  mongo_initdb_root_password : {{ .Values.mongo_initdb_root_password | b64enc | quote}}