# Default values for mongodb-standalone.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

image:
  repository: docker.io/mongodb/mongodb-enterprise-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "5.0.18-ubi8"
  
hostname: mongodb
mongo_initdb_root_username: admin
mongo_initdb_root_password: "Toughpass1!"
containers:
  ports:
    containerPort: 27017

podSecurityContext:
  fsGroup: 101

service:
  type: ClusterIP
  port: 27017

pvc:
  StorageClass: "csi-vmware"
  dbaccessMode: ReadWriteOnce
  dbsize: 5Gi
  dbvolumeMode: Filesystem
  configdbaccessMode: ReadWriteOnce
  configdbsize: 5Gi
  configdbvolumeMode: Filesystem
