apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oracle-standalone.fullname" . }}
  labels:
    {{- include "oracle-standalone.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      {{- include "oracle-standalone.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "oracle-standalone.selectorLabels" . | nindent 8 }}
    spec:
      hostname: {{ .Values.hostname}}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccount: {{ include "oracle-standalone.fullname" . }}
      serviceAccountName: {{ include "oracle-standalone.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: listener
              containerPort: {{ .Values.service.portListener}}
          env:
            - name: ENABLE_ARCHIVELOG
              value: "true"
            - name: ORACLE_PWD
              valueFrom:
               secretKeyRef:
                name: {{ include "oracle-standalone.fullname" . }}-secret
                key: {{  template "oracle.rootpassword" . }}
          volumeMounts:
            - mountPath: /opt/oracle/oradata
              name: oradata
      imagePullSecrets:
        - name: {{ include "oracle-standalone.fullname" . }}-pull-secret
      volumes:
        - name: oradata
          persistentVolumeClaim:
            claimName: {{ include "oracle-standalone.fullname" . }}-oradata
