kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.hostname }}-oradata
spec:
  accessModes:
    - {{ .Values.pvc.oradataaccessMode | quote}}
  resources:
    requests:
      storage: {{ .Values.pvc.oradatasize}}
  storageClassName: {{ .Values.pvc.StorageClass}}
  volumeMode: {{ .Values.pvc.oradatavolumeMode}}