apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.hostname }}-secret
  labels:
    {{- include "oracle-standalone.labels" . | nindent 4 }}
type: Opaque
data:
  oracle_password : {{ .Values.oracle_password | b64enc | quote}}