apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-utils
  name: k8s-utils
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-utils
  template:
    metadata:
      labels:
        app: k8s-utils
    spec:
      containers:
      - image: docker.io/lorenzobiosa/k8s-utils:latest
        name: k8s-utils
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
