apiVersion: v1
kind: Service
metadata:
  labels:
    app: confluentinc-cp-ksql-server
  name: ksql-server
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: ksql-server
    port: 8088
  selector:
    app: confluentinc-cp-ksql-server
