apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: confluentinc-cp-enterprise-kafka
  name: confluentinc-cp-enterprise-kafka
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: confluentinc-cp-enterprise-kafka
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: confluentinc-cp-enterprise-kafka
    spec:
      hostname: broker
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092"
        - name: KAFKA_METRIC_REPORTERS
          value: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS
          value: "broker:29092"
        - name: CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS
          value: "1"
        - name: CONFLUENT_METRICS_ENABLE
          value: "true"
        - name: CONFLUENT_SUPPORT_CUSTOMER_ID
          value: "anonymous"
        image: confluentinc/cp-enterprise-kafka:latest
        imagePullPolicy: Always
        name: broker
        ports:
        - containerPort: 29092
          protocol: TCP
        - containerPort: 9092
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
