apiVersion: v1
kind: Service
metadata:
  labels:
    app: confluentinc-cp-zookeeper
  name: zookeeper
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: zookeeper
    port: 2181
  selector:
    app: confluentinc-cp-zookeeper
