apiVersion: v1
kind: Service
metadata:
  labels:
    app: confluentinc-cp-schema-registry
  name: schema-registry
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: schema-registry
    port: 8081
  selector:
    app: confluentinc-cp-schema-registry
