apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  labels:
    app: confluentinc-cp-kafka-rest
  name: confluentinc-cp-kafka-rest
  namespace: misura-cdc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: confluentinc-cp-kafka-rest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: confluentinc-cp-kafka-rest
    spec:
      hostname: rest-proxy
      containers:
      - env:
        - name: KAFKA_REST_HOST_NAME
          value: rest-proxy
        - name: KAFKA_REST_BOOTSTRAP_SERVERS
          value: "broker:29092"
        - name: KAFKA_REST_LISTENERS
          value: "http://0.0.0.0:8082"
        - name: KAFKA_REST_SCHEMA_REGISTRY_URL
          value: "http://schema-registry:8081"
        image: confluentinc/cp-kafka-rest:5.3.0
        imagePullPolicy: IfNotPresent
        name: rest-proxy
        ports:
        - containerPort: 8082
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
