apiVersion: v1
kind: Service
metadata:
  labels:
    app: confluentinc-cp-kafka-rest
  name: rest-proxy
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: rest-proxy
    port: 8082
  selector:
    app: confluentinc-cp-kafka-rest
