apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mssql-standalone.fullname" . }}-secret
  labels:
    {{- include "mssql-standalone.labels" . | nindent 4 }}
type: Opaque
data:
  sa_password : {{ .Values.sa_password | b64enc | quote}}
