apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-express
  name: mongo-express
  namespace: mongodb-ha
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8081
  publishNotReadyAddresses: true
  selector:
    app: mongo-express
